2022-02-15 09:09:31,461:utility.py:utility:INFO:3
2022-02-15 09:09:31,539:utility.py:utility:INFO:A new credit card has been created.
2022-02-15 09:11:19,608:utility.py:utility:INFO:3
2022-02-15 09:11:19,670:utility.py:utility:INFO:A new credit card has been created.
2022-02-15 09:12:26,433:utility.py:utility:INFO:3
2022-02-15 09:12:26,480:utility.py:utility:INFO:A new credit card has been created.
2022-02-15 09:14:56,103:utility.py:utility:INFO:3
2022-02-15 09:14:56,150:utility.py:utility:INFO:A new credit card has been created.
2022-02-15 09:17:13,611:utility.py:utility:INFO:1
2022-02-15 09:17:13,658:utility.py:utility:INFO:A new credit card has been created.
2022-02-15 09:17:13,689:utility.py:utility:INFO:2
2022-02-15 09:17:13,720:utility.py:utility:INFO:A new credit card has been created.
2022-02-15 09:20:17,851:utility.py:utility:INFO:1
2022-02-15 09:20:17,898:utility.py:utility:INFO:A new credit card has been created.
2022-02-15 09:20:17,914:utility.py:utility:INFO:2
2022-02-15 09:20:17,946:utility.py:utility:INFO:A new credit card has been created.
2022-02-15 09:20:17,961:utility.py:utility:INFO:3
2022-02-15 09:20:17,993:utility.py:utility:INFO:A new credit card has been created.
2022-02-15 09:25:17,934:utility.py:utility:INFO:3
2022-02-15 09:25:17,981:utility.py:utility:INFO:A new credit card has been created.
2022-02-15 15:00:50,857:utility.py:utility:INFO:7
2022-02-15 15:00:51,107:utility.py:utility:INFO:7
2022-02-15 15:33:10,831:utility.py:utility:INFO:1
2022-02-15 15:33:10,909:utility.py:utility:INFO:A new credit card has been created.
2022-02-15 15:33:10,940:utility.py:utility:INFO:2
2022-02-15 15:33:10,972:utility.py:utility:INFO:A new credit card has been created.
2022-02-15 15:33:10,988:utility.py:utility:INFO:3
2022-02-15 15:33:11,003:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 06:51:59,616:utility.py:utility:INFO:1
2022-02-16 06:51:59,679:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 06:51:59,710:utility.py:utility:INFO:2
2022-02-16 06:51:59,741:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 06:51:59,773:utility.py:utility:INFO:3
2022-02-16 06:51:59,810:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 07:31:11,027:utility.py:utility:INFO:1
2022-02-16 07:31:11,073:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 07:31:11,104:utility.py:utility:INFO:2
2022-02-16 07:31:11,121:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 07:31:11,152:utility.py:utility:INFO:3
2022-02-16 07:31:11,178:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 07:39:08,925:utility.py:utility:INFO:1
2022-02-16 07:39:08,972:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 07:47:25,433:utility.py:utility:INFO:2
2022-02-16 07:47:25,511:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 08:11:32,782:utility.py:utility:INFO:1
2022-02-16 08:11:32,829:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 08:11:32,844:utility.py:utility:INFO:2
2022-02-16 08:11:32,876:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 08:11:32,907:utility.py:utility:INFO:3
2022-02-16 08:11:32,941:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 08:14:13,814:utility.py:utility:INFO:1
2022-02-16 08:14:13,861:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 08:14:13,877:utility.py:utility:INFO:2
2022-02-16 08:14:13,923:utility.py:utility:INFO:A new credit card has been created.
2022-02-16 08:14:13,939:utility.py:utility:INFO:3
2022-02-16 08:14:13,970:utility.py:utility:INFO:A new credit card has been created.
2022-02-17 12:33:17,462:utility.py:utility:INFO:169
2022-02-17 12:33:17,478:utility.py:utility:INFO:No row was found when one was required
2022-02-17 12:33:17,478:utility.py:utility:INFO:144
2022-02-17 12:33:17,478:utility.py:utility:INFO:No row was found when one was required
2022-02-17 12:33:42,893:utility.py:utility:INFO:169
2022-02-17 12:33:42,893:utility.py:utility:INFO:No row was found when one was required
2022-02-17 12:33:42,893:utility.py:utility:INFO:144
2022-02-17 12:33:42,893:utility.py:utility:INFO:No row was found when one was required
2022-02-17 12:34:14,716:utility.py:utility:INFO:1
2022-02-17 12:34:14,731:utility.py:utility:INFO:144
2022-02-17 12:34:14,731:utility.py:utility:INFO:No row was found when one was required
2022-02-17 12:34:19,299:utility.py:utility:INFO:1
2022-02-17 12:34:19,299:utility.py:utility:INFO:144
2022-02-17 12:34:19,299:utility.py:utility:INFO:No row was found when one was required
2022-02-17 12:34:57,320:utility.py:utility:INFO:1
2022-02-17 12:34:57,320:utility.py:utility:INFO:144
2022-02-17 12:34:57,320:utility.py:utility:INFO:No row was found when one was required
2022-02-17 12:35:46,039:utility.py:utility:INFO:1
2022-02-17 12:35:46,039:utility.py:utility:INFO:144
2022-02-17 12:35:46,039:utility.py:utility:INFO:No row was found when one was required
2022-02-17 12:38:11,647:utility.py:utility:INFO:1
2022-02-17 12:38:11,647:utility.py:utility:INFO:144
2022-02-17 12:38:11,647:utility.py:utility:INFO:No row was found when one was required
2022-02-17 12:38:18,392:utility.py:utility:INFO:1
2022-02-17 12:38:18,393:utility.py:utility:INFO:144
2022-02-17 12:38:18,394:utility.py:utility:INFO:No row was found when one was required
2022-02-17 12:39:02,120:utility.py:utility:INFO:1
2022-02-17 12:39:02,120:utility.py:utility:INFO:144
2022-02-17 12:39:02,120:utility.py:utility:INFO:No row was found when one was required
2022-02-17 12:48:08,502:utility.py:utility:INFO:1
2022-02-17 12:48:08,502:utility.py:utility:INFO:144
2022-02-17 12:48:08,502:utility.py:utility:INFO:No row was found when one was required
2022-02-17 12:58:28,144:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2022-02-17 12:58:28,295:utility.py:utility:INFO:1
2022-02-17 12:58:28,311:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2022-02-17 13:00:57,456:utility.py:utility:INFO:1
2022-02-17 13:00:57,456:utility.py:utility:INFO:144
2022-02-17 13:00:57,456:utility.py:utility:INFO:No row was found when one was required
2022-02-17 13:02:59,200:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2022-02-17 13:02:59,294:utility.py:utility:INFO:1
2022-02-17 13:02:59,310:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2022-02-17 13:04:00,847:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2022-02-17 13:04:00,941:utility.py:utility:INFO:1
2022-02-17 13:04:00,956:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2022-02-17 13:07:01,612:utility.py:utility:INFO:1
2022-02-17 13:07:01,612:utility.py:utility:INFO:144
2022-02-17 13:07:01,612:utility.py:utility:INFO:No row was found when one was required
2022-02-17 13:07:16,568:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2022-02-17 13:07:16,708:utility.py:utility:INFO:1
2022-02-17 13:07:16,724:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2022-02-17 13:09:45,827:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2022-02-17 13:12:10,732:utility.py:utility:INFO:(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([WinError 10061] No connection could be made because the target machine actively refused it)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-02-17 13:13:35,240:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2022-02-17 13:13:35,318:utility.py:utility:INFO:1
2022-02-17 13:13:35,334:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2022-02-17 13:14:14,354:utility.py:utility:INFO:1
2022-02-17 13:14:14,354:utility.py:utility:INFO:144
2022-02-17 13:14:14,354:utility.py:utility:INFO:No row was found when one was required
2022-02-17 13:14:45,657:utility.py:utility:INFO:(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'loca2lhost' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-02-17 13:14:55,358:utility.py:utility:INFO:(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'loca2lhost' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-02-17 13:14:55,436:utility.py:utility:INFO:1
2022-02-17 13:14:57,721:utility.py:utility:INFO:(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'loca2lhost' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-02-17 13:16:28,382:utility.py:utility:INFO:(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([WinError 10061] No connection could be made because the target machine actively refused it)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-02-17 13:16:28,460:utility.py:utility:INFO:1
2022-02-17 13:16:32,542:utility.py:utility:INFO:(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([WinError 10061] No connection could be made because the target machine actively refused it)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-02-17 13:16:47,240:utility.py:utility:INFO:1
2022-02-17 13:16:47,240:utility.py:utility:INFO:144
2022-02-17 13:16:47,240:utility.py:utility:INFO:No row was found when one was required
2022-02-17 13:17:10,013:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2022-02-17 13:18:19,693:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2022-02-17 13:18:47,532:utility.py:utility:INFO:'cryptography' package is required for sha256_password or caching_sha2_password auth methods
